
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/USERNAME/devops-portfolio
    newTag: latest
nameSuffix: -prod
namespace: prod
patches:
  - target:
      version: v1
      kind: Deployment
      name: devops-portfolio
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
